# Generated by Django 5.0.3 on 2024-04-01 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='payment_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='myapp.systemuser'),
        ),
    ]
