# Generated by Django 5.0.3 on 2024-04-04 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_timesheet_payment_status_alter_timesheet_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='username',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
