# Generated by Django 5.0.4 on 2024-04-08 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_timesheet_payment_status_alter_timesheet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timesheet',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(default='2024-04-08', max_length=30),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 4, 14)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 4, 8)),
        ),
    ]
