# Generated by Django 5.0.4 on 2024-04-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_event_timesheet_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timesheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.timesheet'),
            preserve_default=False,
        ),
    ]
