# Generated by Django 5.0.3 on 2024-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_systemuser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='user',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='password',
            field=models.CharField(default='pass', max_length=128),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='username',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
