# Generated by Django 5.0.4 on 2024-04-10 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Meeting', 'Meeting'), ('Project', 'Project'), ('None', 'None')], default='Planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(default='2024-04-10', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(11, 25, 32, 642778)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(11, 25, 32, 642778)),
        ),
    ]
